### ISSUE TITLE
Facebook permissions

### ISSUE THREAD

**Issue by jamacoe** [dejanstojanovic/Facebook-Album-Browser#10]
Hello,
I can't access my facebook albums. I changed natgeo to my fb name. The only thing that is displayed is my profil picture and my user name. 
I read about the instruction to allow **user_photos**. However, I am not into app programming and have no idea what to do. I want to use your plug in from a html website, not from an app, so how am I supposed to grant rights to an app?

**Comment by dejanstojanovic** [comment]
Hi,  apparently there is a problem with permissions for photos for private account. Please create FB page and reference it in plugin initialization

**Comment by dejanstojanovic** [comment]
Let me know if my previous comment helped

**Comment by jamacoe** [comment]
Yes, thank you! With a non-private page I got the photos immediately, without further settings. Will there be a fix for private accounts?

**Comment by dejanstojanovic** [comment]
I was trying to make it work somehow, but every time I end up with exception thrown by OpenGraph. Hopefully I'll find a way to do it and as soon as it happens I will update the plugin
