### ISSUE TITLE
share photo

### ISSUE THREAD

**Issue by dchicon** [dejanstojanovic/Facebook-Album-Browser#11]
Hello!
maybe the possibility to add a "share menu" on each image opened (facebook, whatsapp, twitter, mail,..)? using the photochecked function perhaps?
help please!

**Comment by dejanstojanovic** [comment]
I enabled facebook share button as an addition to like button. How ever I did not plan to add other share buttons soon.
I will consider this for future updates for plugin. If you would like to participate you can make the change and initiate a pull request.
