### ISSUE TITLE
Is this plugin working still?

### ISSUE THREAD

**Issue by rockyr1** [dejanstojanovic/Facebook-Album-Browser#12]
Looks like FB changed their privacy settings or something, this plugin doesnt seem to work anymore. I have checked all the demos online and offline as well. Albums are not visible, only accountinfo shows up. Is there a way around it?

**Comment by dejanstojanovic** [comment]
I think you need to generate the token and add it when you initialize the plugin. I will update the demos soon

**Comment by lanner** [comment]
hello where is the token access for a page fb ? thanks

**Comment by rockyr1** [comment]
Thanks! here are the instructions i followed to Create accesstoken on Facebook
http://doityaar.com/2015/06/how-to-get-facebook-access-token/

**Comment by rockyr1** [comment]
btw acessToken for plugin option is mis-spelled. Should be acCessToken ;-)

**Comment by dejanstojanovic** [comment]
My typo, will do a quick fix, thx :)

**Comment by rockyr1** [comment]
no problem. Thanks!

**Comment by lanner** [comment]
hello
if i understand, now it's impossible to use this Facebook-Album-Browser without an accesstoken ?
do you know a functional solution to automaticly have this token ?
thanks

**Comment by dejanstojanovic** [comment]
I am checking this option now. It's a bit bad thing that Facebook changed their policy since it will cause a lot of existing website functionalities to fail working.

Anyway, I'm looking into some easy to implement change to make this plugin work, but in the meanwhile I will include text from @rockyr1 blog article into README.MD

**Comment by ArrayG** [comment]
Is there a delay from when accesstoken is generated to when it is active? I'm using test.html in the package and replaced the account and accesstoken with my own but it is not working. Followed the instructions on getting accesstoken from README.MD. When loading the page only the profile pic shows but albums do not load. When using original options in test.html(natgeo account), albums from the natgeo account loads.

test page is at http://exquisitememoriesph.com/test.html

**Comment by dejanstojanovic** [comment]
Not sure, try to re-generate your token again. I opened the demo page in plunker http://plnkr.co/edit/bpcaagDgxVClt1lsDH5a?p=preview and instead of **natgeo** I used you your's **exquisitememoriesphotographyand** it worked
