### ISSUE TITLE
GROUP  page

### ISSUE THREAD

**Issue by comtronix** [dejanstojanovic/Facebook-Album-Browser#14]
Can i use the script to get the images from a group page? (public photo's and albums?).

**Comment by dejanstojanovic** [comment]
HI, I haven't tried to use it with the groups. You can give it a try. Recently Facebook updated their security policy, so I'm not sure how it will behave.
Regarding your public photos, you can use but you need to do a lot of things with facebook app. I did this once and as far as I remember, I had to write a request to facebook to enable special permissions for my fb app to read albums, then I had to access the app on my side and use the token in plugin. Pretty complicated but it is doable :)
So far, all the people who used the plugin used it with the page

**Comment by dejanstojanovic** [comment]
Any updates on this? Have you tried to use the plugin for group page?
