### ISSUE TITLE
Popup not correct

### ISSUE THREAD

**Issue by comtronix** [dejanstojanovic/Facebook-Album-Browser#15]
When imagepopup shows the like button is out of the box.
![knipsel](https://cloud.githubusercontent.com/assets/3840400/8639430/2314de8c-28da-11e5-95bf-8004175f9915.PNG)

**Comment by dejanstojanovic** [comment]
Thanks for reporting the issue, I will update status as soon as I manage to fix this layout issue.

**Comment by dejanstojanovic** [comment]
Hello, I'm still struggling to setup the CSS for this problem. Advanced CSS is not really my stronger side :). If you manage somehow to make it look properly, please share.
In case generated HTML structure needs to be updated to resolve this, please let me know so I can update it.
Thank in advance for help
