### ISSUE TITLE
About the 'user_photos permission'

### ISSUE THREAD

**Issue by riotbr** [dejanstojanovic/Facebook-Album-Browser#16]
First of all, great job and thanks for sharing it.

About the 'user_photos permission', it is required only when creating a new app to get a proper access token, right? It seems to be a thing with the API version 2.4. Why? When using an access token of an old app (API version 2.0) that doesn't have the 'user_photos permission', the plugin works beautifully.

I would like to create a new app for the plugin, a proper one, but Facebook requirements for this item approval it's a herculean task =P

Thanks in advance for any comment or tip. Btw, sorry about my english ;)

**Comment by dejanstojanovic** [comment]
Hi, 'user_photos' permission is only required if you want to browse your personal account photos as far as I know. For pages is a bot easier as you do not need this.
Since last update, Facebook requires to include accessToken when calling OpenGraph. The plugin has this option, only token needs to be provided from the Facebook app.
Hopefully I answered your question.
Let me know if you have any issues

**Comment by dejanstojanovic** [comment]
Since there is no reply for this issue for longer time, I'm closing it

**Comment by MarkusMaximusBC** [comment]
Hi,

I'm having problems with this as well. I follow the steps to create an app but I can't apply the user_photos permission without submitting it to facebook for approval. they reject it and tell me it's meant for a program with a user login?? Is there something I'm missing or has facebook tightened thing up even more? 

Thanks!

**Comment by dejanstojanovic** [comment]
Hi @MarkusMaximusBC in case you want to display account photos, you will have to go through painful Facebook app permission approval process :(
In case you have a page and want to display albums and images from it, you can just create your Facebook app and use it's token.
I hope I helped

**Comment by MarkusMaximusBC** [comment]
But how do I get facebook to approve? this is what the said:
"You don’t need any extended permissions for an app that you admin. App admins, and any account listed as a ‘role’ in the App Settings page, can access all permissions without submitting for review. This means you can publish contact back to Facebook for your app. You only need to submit for review if you have a public facing login."

Your app doesn't have a public facing login so how do I convince them to allow it?

**Comment by dejanstojanovic** [comment]
Ok, it makes sense not to get approval if you are using it for your account only.
We just need to figure out how to give permission to this app to your own account and then use it's token to get images.
I'll try the same thing with my account and see what I can come up with.

**Comment by MarkusMaximusBC** [comment]
ok thanks. what I have is a personal account with a business page attached to it. I guess that is why I'm having the problems. I don't want the images from my personal feed, only the ones from my business page.

**Comment by dejanstojanovic** [comment]
That should not be the problem, most people use it with pages. Check comments in issue #13 where you have posted URL where plugin has been used

**Comment by MarkusMaximusBC** [comment]
I tried all the steps to create a token and have that working but It won't display any photos. You can see what it does by viewing the page: http://vancouverdiamonds.ca/pictures

**Comment by MarkusMaximusBC** [comment]
I don't really know what else to try. Can you try creating a brand new app and see if you have any issues?

**Comment by dejanstojanovic** [comment]
Ok, let me try somehow to make it work.
Can you please send me the token and script for initialization of the plugin to my email.
Go to my blog dejanstojanovic.net and send me all these in a contact form for the about section on the website. I will reply to you to email you used in that form.

A bit complicated but at least I do not share my email publicly :)

**Comment by MarkusMaximusBC** [comment]
tried and got an error 500 after submitting the message. tried on chrome and internet explorer.

**Comment by dejanstojanovic** [comment]
:( I just tried and sent mail to my self
I'll have to upgrade my host soon because of things like this :)
Try a gain in few minutes, if not working add me on G+ https://plus.google.com/u/0/108404484724048935794

**Comment by dejanstojanovic** [comment]
We found the issue, access token used is wrong, I will update the steps to get the proper access token soon

**Comment by timracer** [comment]
Good! I will wait. Are you update it today?

**Comment by dejanstojanovic** [comment]
Check out now, I double checked and managed to generate new access token for a new test app. Let me know if you manage to do it.
Please close the issue if it worked for you, or we'll continue chat :)

**Comment by timracer** [comment]
How to know does the app has permissions to user photo? Maybe it doesn't so thats why it still doesn't work for me...

**Comment by dejanstojanovic** [comment]
It looks like it has something to do with API version of the App. The app used for demo is v2.2 and it works fine. The new one I just created for test is v2.4. Let me try to downgrade the version call to v2.2 for v2.4 app if it is possible.
Otherwise, I'll have to update the code a lot :(

**Comment by timracer** [comment]
Thank you for your plugin! i wish you good luck with API versions war! And if it will work with API 2.4, I will use it on my personal website and will share a link in suitable issue

**Comment by dejanstojanovic** [comment]
In issue #25 people offered to make the change for new API version, so either they make the change or I will as soon as I find some time.
If you need to use the plugin urgently, feel free to  use it with token provided in demo. Should not make differences except you will not be able to track frequency of use and stuff like that, but should work normally until I make the update
Will update you on this..

**Comment by dejanstojanovic** [comment]
I added support for v2.4, so it should work now with both old and new apps
