### ISSUE TITLE
function request

### ISSUE THREAD

**Issue by comtronix** [dejanstojanovic/Facebook-Album-Browser#18]
can you add an option for displaying the comments @ a picture?
it would be nice if the popup can display the image and comments in 1 popup

**Comment by dejanstojanovic** [comment]
Good idea,

I was thinking of something like that to include in plugin. Hopefully I'll fine some free time soon to add this.
Stay tuned

**Comment by dejanstojanovic** [comment]
Hello, I just finished adding comments option to image preview. Please check and report if you find any issue.
Album comments options is not yet implemented, but as soon as it does I will update

**Comment by comtronix** [comment]
thank you for the update. ill test asap. My css knowlegde is poor. i know something about php and a little of js, but that's al.. sorry. mabey someone else can help you out fixing the css.
