### ISSUE TITLE
Dates @usercomments are NULL on IPAD

### ISSUE THREAD

**Issue by comtronix** [dejanstojanovic/Facebook-Album-Browser#19]
There is a bug with the display of comments by the pictures.

On computer the dates are OK , on IPAD the dates @comments are 1 january 1970 or all null null null null null null null nul:null

**Comment by dejanstojanovic** [comment]
Thanks man, I'll check on Safari

**Comment by dejanstojanovic** [comment]
On Yosemiti it works well in Safari except the date format is long date time which does not look so nice :(. I will try to add a date format support.
For the iPad issue, I'll have to check on the device it self

**Comment by dejanstojanovic** [comment]
Code change for DateTime parsing check in. Please report if issue still exeists
