### ISSUE TITLE
share photos from lightbox

### ISSUE THREAD

**Issue by dchicon** [dejanstojanovic/Facebook-Album-Browser#22]
Hello Dejan!
I still tying  to share the images from lightbox.... 
I try to do it using addthis, but i can´t.
They tell me that I´ve to call the addthis.init(); and addthis.layers.refresh(); functions in the same function that loads the lightbox... No idea of how to do it, and not much help in google

Those are the codes they give me to put into the body of the html.

	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-50360b776f77c6a6" async="async"></script>

    <div id ="botones" class="addthis_sharing_toolbox"></div>

Thank you

**Comment by dejanstojanovic** [comment]
Hi,
The answer you got is correct, this method needs to be called every time new image is loaded. Since I am using a custom code for a light box, adding AddThis elements and its initialization needs to be done in this custom code I wrote in order to support AddThis.

Find function addLikeButton (line 464). This is basically the place where you need to dynamically add your AddThis html and initialize AddThis code. 
Let me know if this helped.

**Comment by dchicon** [comment]
Hi Dejan, Thanks for the answer.
The problem is that I´m not a developer,( not pro, only amateur. I´m graphic designer) so it´s really difficult for me to change the code because first I´ve to research in google, and as i told you, not much help with addthis.init() and addthis.layers.refresh().
Some extra help, please?
Thank you very much

**Comment by dejanstojanovic** [comment]
No problem man, 
I'll try to add this thing as an option for the plugin. I already started doing some code, so hopefully soon it will be there.
Will let you know

**Comment by dchicon** [comment]
Great!
you're invited to some beers in Spain  when you wanna!

**Comment by dejanstojanovic** [comment]
Give it a try now.
Set shareButton to true and addThis to your AddTHis public id from your account.
You can check sample test page in this solution as it has these settings which I used to do testing.
Let me know if you spot any issue

**Comment by dchicon** [comment]
It doesn´t work. Addthis don´t appears

**Comment by dejanstojanovic** [comment]
That is weird. Make sure you took the latest code from the GitHub.
Make sure you are running page from some local web server, IIS Expressor XAMP or what ever you have on your machine.
Can you send me the HTML code which you use to initialize plugin on your page?

**Comment by dchicon** [comment]
I test it on Plunker, and i load your code into my server.

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://www.applicare.es/php/mile/jquery.fb.albumbrowser.js"></script>
    <link rel="stylesheet" type="text/css" href="http://www.applicare.es/php/mile/jquery.fb.albumbrowser.css" />
</head>

<body>
    <div class="fb-album-container"></div>

    <script type="text/javascript">
        $(document).ready(function () {
          $(".fb-album-container").FacebookAlbumBrowser({
                account: "TIERRACAFE",
                accessToken: "871028626302917|D52bS7KyJaluNK6KH4YgzmQLcRI",
                skipAlbums: ["Profile Pictures", "Timeline Photos"],
                //onlyAlbum: "10150310813623951",
                showComments: true,
                commentsLimit:3,
                showAccountInfo: true,
                showImageCount: true,
                showImageText: true,
                shareButton: true,
                albumsPageSize: 0,
                photosPageSize: 0,
                lightbox: true,
                photosCheckbox: true,
                likeButton: true,
                shareButton: true,
                addThis:"ra-50360b776f77c6a6",
                photoChecked: function(photo){
                    console.log("PHOTO CHECKED: " + photo.id + " - " + photo.url + " - " + photo.thumb);
                    console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
                },
                photoUnchecked: function (photo) {
                    console.log("PHOTO UNCHECKED: " + photo.id + " - " + photo.url + " - " + photo.thumb);
                    console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
                },
                albumSelected: function (photo) {
                    console.log("ALBUM CLICK: " + photo.id + " - " + photo.url + " - " + photo.thumb);
                },
                photoSelected: function (photo) {
                    console.log("PHOTO CLICK: " + photo.id + " - " + photo.url + " - " + photo.thumb);
                }
            });

        });
    </script>
</body>
</html>

**Comment by dchicon** [comment]
how to attach a html code?

**Comment by dchicon** [comment]
Sent. Thanks again, Dejan

**Comment by dejanstojanovic** [comment]
I did the same test in Plunker demo and it worked. Check the screenshot
![addthis](https://cloud.githubusercontent.com/assets/7481783/9058493/9f868940-3ab2-11e5-847f-f1a5c5d3dc0b.png)
I just added addThis value, the same one you provided

**Comment by dejanstojanovic** [comment]
By the way, take the latest as I just updated code for updating dynamically AddThis url

**Comment by dchicon** [comment]
ufff... gremlins invades my imac.
with your new test.html and  codes loaded into my server... it´s doesn´t work!!
I fell like a stupid.
![captura de pantalla 2015-08-04 a la s 12 45 14](https://cloud.githubusercontent.com/assets/7935643/9059032/bb95eb5a-3aa6-11e5-8e4b-cb3fbb7256c3.png)

**Comment by dchicon** [comment]
There are 2 shareButtons options in test.html. Is it ok?

**Comment by dejanstojanovic** [comment]
Relax, we'll find what is wrong, no worries :)
I think number of buttons depends on the settings you have related to your pub-id from AddThis. I believe you can add more through AddThis settings when you login to their dashboard.
Check with pub-id I added in test.html, that one for sure has 4 buttons. By the way, I limited number of buttons to 4, so in case you have more it will only show up only first 4 :)

**Comment by dchicon** [comment]
tested with your test.html, and codes uploads into my server.
Broken arrow again :(
I think gremlins are taking a bath into motherboard. Can´t you hear the party?
![captura de pantalla 2015-08-04 a la s 13 16 11](https://cloud.githubusercontent.com/assets/7935643/9059534/37750266-3aab-11e5-9d11-1def3a0372fd.png)

**Comment by dchicon** [comment]
look:
if i click your "checkout demo on plunker" and i change the body for the one of your new test.html... It´s work!!

**Comment by dejanstojanovic** [comment]
OK, let's do it this way. Since I used test.html to test and develop everything, grab latest from GitHub, set it up and run on your machine. Than one should work definitely.

I am pretty sure it has something to do with the cached stuff in a browser, but just to make sure, run the code from GitHub on you local and let me know if you are still experiencing any issues

**Comment by comtronix** [comment]
``ufff... gremlins invades my imac.
with your new test.html and codes loaded into my server... it´s doesn´t work!!
I fell like a stupid.``
dchicon : please define 'stupid'..

Lolz

**Comment by dchicon** [comment]
Hi Dejan.
Tested on a local host:
with the code of your server it work,  and addThis too;  but if a I load the actual version of the code into my server... it doesn´t work.

**Comment by dejanstojanovic** [comment]
Is there any JavaScript error reported by the browser?

**Comment by dchicon** [comment]
Sorry Dejan!, It works now perfectly with your code and  css loaded on my server!
Yeeeah!!
Take a look

**Comment by dejanstojanovic** [comment]
Great. Let me know if you find any issue
