### ISSUE TITLE
Add option to images folder path

### ISSUE THREAD

**Issue by danielemesh** [dejanstojanovic/Facebook-Album-Browser#24]
I think you should add an option to set an images folder path.
In my case, I have an images folder for all the images in my projects, so I added to the defaults object a new property:
```
var defaults = {
            account: "",
            ...
            checkedPhotos: [],
            imagesPath: "src/"
        }
```
And then on lines : 178, 508, 509
I changed the **src** attr to:
```
src: settings.imagesPath + "whatever-image-needed.png"
```

BTW - your plugin is awesome!

**Comment by dejanstojanovic** [comment]
Sounds useful, I will add it

**Comment by dejanstojanovic** [comment]
Added option pluginImagesPath for images used for plugin UI. Default value is 'src/'
