### ISSUE TITLE
Selecting Albums for Viewing

### ISSUE THREAD

**Issue by lukepsauer** [dejanstojanovic/Facebook-Album-Browser#28]
Hello again,

I am trying to select a couple of albums only to show in a gallery is there an easy way to do this?

Thank you

**Comment by dejanstojanovic** [comment]
There is an option to exclude albums from the layout, so you can exclude the ones you do not want to show. Check the description for skipAlbums option.
Let me know if this works for you. Maybe an option which does the oposite (shows listed albums only) makes more sense

**Comment by lukepsauer** [comment]
The issue with that is that I am adding more albums quite frequently and do not want to have to edit the page every time a new one is posted.

**Comment by lukepsauer** [comment]
So an option that does the opposite would be amazing.

**Comment by dejanstojanovic** [comment]
Ok, so you wold like to list the albums which will be the only ones to be loaded, so when you add and album on the Facebook page it does not affect the page where the plugin is used, correct?

**Comment by lukepsauer** [comment]
Correct

**Comment by dejanstojanovic** [comment]
Hi, I made an update for this issue. Take the latest ante try it out. You only need to set includeAlbums option.
Check the test.html file for usage of this.
Please close the issue if this resolves your problem.

**Comment by dejanstojanovic** [comment]
@lukepsauer have you checked the update related to this?
