### ISSUE TITLE
Multiple albums of the same page

### ISSUE THREAD

**Issue by sDamme** [dejanstojanovic/Facebook-Album-Browser#30]
My issue is that I have a single page website but what I wanted to do is display 3 different albums in 3 different sections from the same page on the website. 
When I try that, instead of getting 3 different albums in 3 different sections, they all merge only in 1 section.
You can check this at http://sander2.alimit.com/assets/index.html
I apologize the site is in Estonian. You have to scroll down to "Meeskond" and in the right side click on "Näita tehtud tööd". So there are 3 buttons like that but only the middle one works and it takes all the albums as one.
I'd like to mention that my coding isn't the best and I'm still a newbie when it comes to all this so I'm sure it's something obvious I did wrong. Certainly willing to learn more and understand how everything works.

**Comment by dejanstojanovic** [comment]
There is an option for the plug in named onlyAlbum which  accepts album Id. This will load only images from the specific album. 
Now there might be a bug with multiple instances of the plug in on the same page. I'll check this

**Comment by sDamme** [comment]
Oh ye, I did use the onlyAlbum specifically for each album and they all merged into one. 
I also tried skipAlbums for each instance, so maybe it would remove the 2 extra albums from each of the 3 sections but that also proved unsuccessful.
I think it might be with the onlyAlbum plug-in. Thanks for looking into this.

**Comment by dejanstojanovic** [comment]
There was no bug, it is working fine.
I added one more file to name test-multiple.html, get latest from the repository and try it out.
Let me know if it works for you so I can close the issue, or close it yourself it you find this thing working for you as expected.

**Comment by sDamme** [comment]
Yeah, it worked exactly as I wanted. As I said I am not that good with coding and I just couldn't figure out the way to do it. Thank you very very much for taking your time with this. It definitely means a lot to me. :)
Case closed

**Comment by dejanstojanovic** [comment]
@sDamme I found a small issue with lazy image loading when using onlyAlbum option, please take the latest to avoid problems
