### ISSUE TITLE
share buttons row

### ISSUE THREAD

**Issue by timracer** [dejanstojanovic/Facebook-Album-Browser#32]
Hi! When watching photo into lightbox it seems something wrong with share buttons because it's duplicates constantly, when I click NEXT or PREV arrows, it's always increases (+1) rows of share buttons. What should it be?

**Comment by timracer** [comment]
Something like that
![267](https://cloud.githubusercontent.com/assets/6567906/9753166/eeabec38-56da-11e5-92c1-068e4ab5587b.png)

**Comment by timracer** [comment]
Something like that
![267](https://cloud.githubusercontent.com/assets/6567906/9753179/1585b3b6-56db-11e5-8e9e-047dad319b92.png)

**Comment by dejanstojanovic** [comment]
It looks like the handle is duplicated on the arrow buttons which initializes the share plugin. Try to debug with Firebug to see if method addLikeButton is called multiple times which is most probably the case

**Comment by dejanstojanovic** [comment]
I just saw that like button is missing. I will check that

**Comment by timracer** [comment]
Like button is missing because I switched likeButton settings to false
