### ISSUE TITLE
Read videos

### ISSUE THREAD

**Issue by lanner** [dejanstojanovic/Facebook-Album-Browser#4]
Hello
If i put photos and videos on an album of my page, does your script read the videos ?
Thanks

**Comment by dejanstojanovic** [comment]
I'm pretty sure it will not handle videos, but good idea for a new feature to include in plugin

**Comment by dejanstojanovic** [comment]
Is there a way to combine images and videos in Facebook album?

**Comment by lanner** [comment]
Ouch maybe not :)

**Comment by dejanstojanovic** [comment]
Thanks. Fell free to give a feedback about the thinks that might be included in it
