### ISSUE TITLE
Facebook ID undefined. 

### ISSUE THREAD

**Issue by babooth** [dejanstojanovic/Facebook-Album-Browser#41]
Thank you for the great script. I have been searching high and low for something like this and this fits perfectly.

The script worked perfectly at first. It managed to display the albums on my facebook page. (http://babooth.com.sg/halloffame.html and www.fb.com/sg.babooth)
However, after i tried access it about an hour later it seemed not able to load. (see attached)

If i clicked on the logo in the page, i get and error from facebook and it pushes me to this page (https://www.facebook.com/undefined?_rdr=p) 

I followed the instructions as per the page to get the album Id and access token. Is there something i'm doing wrong? 

![image](https://cloud.githubusercontent.com/assets/16149312/11586128/d1eea7ce-9aab-11e5-8776-ab487d20b3e6.png)

**Comment by comtronix** [comment]
i think the token is expired

**Comment by babooth** [comment]
Newbie mistake. Thank you Comtronix for your help on this.

Here are the instructions on how to create a perm access token.
http://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token
