### ISSUE TITLE
photosCheckbox

### ISSUE THREAD

**Issue by lanner** [dejanstojanovic/Facebook-Album-Browser#5]
Hello
I don't understand what the photosCheckbox do if it enabled
Thanks :)

**Comment by dejanstojanovic** [comment]
It collects images you picked into an array,  so you can use them. You can use plugin as a picker with preview if you enable it

**Comment by lanner** [comment]
can you explain a little more, cause i don't have really undestand, where did you "picked into an array" ?
thanks

**Comment by dejanstojanovic** [comment]
First If you check photo, you will have event "photoChecked" raised from the plugin. All checked images (at least meta of the image with id and url) are stored in plugin array "checkedPhotos" (line 17 of the current version of jquery.fb.albumbrowser.js)

I hope this helped you. As soon as I find some time, I'll add this with more details to documentation.
