### ISSUE TITLE
jQuery 3

### ISSUE THREAD

**Issue by fritzdacat** [dejanstojanovic/Facebook-Album-Browser#54]
Facebook-Album-Browser is not working with jQuery 3.

Error:
TypeError: url.indexOf is not a function
off = url.indexOf( " " );

**Comment by dejanstojanovic** [comment]
Hi @fritzdacat I haven update this project for a long time, so it is possible that it is not working with latest JQuery. I hope I will get some time to sit and work on the current issues and make an update for the latest JQuery version
