### ISSUE TITLE
FBAB Works on local site, but not web host

### ISSUE THREAD

**Issue by Samg381** [dejanstojanovic/Facebook-Album-Browser#65]
Hello,

I run a website through Network Solutions, and a local testing server on an old PC.

The Album browser works great on my local site, but fails to appear on the web host.
Any ideas of what the issue could be?

Here are the links:

Working local server: http://100.35.147.197/gallery.php
Broken web host: https://04052af.netsolhost.com/gallery

**Comment by zsavicreative** [comment]
```
Mixed Content: The page at 'https://04052af.netsolhost.com/gallery' was loaded over HTTPS, but requested an insecure script 
'http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'. 
This request has been blocked; the content must be served over HTTPS.

Uncaught ReferenceError: jQuery is not defined
    at jquery.fb.albumbrowser.js:811
gallery:98 

Uncaught ReferenceError: $ is not defined
    at gallery:98
```

thats from the console when I go to your link
so what it looks like to me is that you havent linked jquery library properly. Go through all your code and check to see if your link actually points to a jquery version that this plugin uses. Just verify that its all linked properly, cause that error tells me that your code isnt detecting the script link. Also it isn't detecting a link for jquery.fb.albumbrowser.js so these errors arent from the plugin, its your structure.

**Comment by Samg381** [comment]
I've made some progress, but I'm still stuck.
I found out my code is working fine.

The issue is something to do with HTTP vs HTTPS and SSL connections.
When I click 'allow unknown sources' in google chrome, it works perfectly.
What should I do to address this with my web host? Thanks.

**Comment by Samg381** [comment]
Think I may have figured it out. I downloaded the jquery library directly to the local server and it appears to be working now. Let me know if it works on your end. I appreciate the help!

**Comment by zsavicreative** [comment]
yes I can see the gallery now

**Comment by Samg381** [comment]
Thank you.

**Comment by zsavicreative** [comment]
glad I could help
