### ISSUE TITLE
Can't get album to load for account

### ISSUE THREAD

**Issue by cobygifford** [dejanstojanovic/Facebook-Album-Browser#70]
Can't seem to figure out what I am doing wrong.
I opened your codepen page for testing.
Won't seem to load for this facebook account below and their albums are public.
JR-Landscaping-Lawn-Service-780219571998457
I'd love to use this plug in because it looks awesome and cycles all albums.

![image](https://user-images.githubusercontent.com/30001308/36861323-68e070e8-1d38-11e8-9d27-6016af417630.png)

**Comment by kawstuv** [comment]
Thanks for the code it has been a great help, however, currently the facebook albums are not loading only the thumbnail appears. This is not only for me but everywhere it is happening wherever demo is given. Check this link:
http://demo.technoworkshop.in/facebook-album-browser/

https://www.jqueryscript.net/gallery/jQuery-Plugin-To-Display-Facebook-Albums-Photos-On-Your-Website.html

**Comment by dejanstojanovic** [comment]
The reason for this is Application API call rate breached.
I created a sample app for demo purpose on Facebook, but apparently a lot of people are using this during development or some other purpose which is causing limit to be breached
![image](https://user-images.githubusercontent.com/7481783/40887143-0531c116-6755-11e8-80a5-66cc515db902.png)

**Comment by kawstuv** [comment]
Thanks for your help.

**Comment by kawstuv** [comment]
So, what is the way out???

**Comment by dejanstojanovic** [comment]
Alternatively, you can register your own Facebook application and use it instead of the demo one I registered

**Comment by kawstuv** [comment]
Got it Sir, thanks let me try and get back to you.

**Comment by zsavicreative** [comment]
I think it goes without saying, the only way to run this plugin in a stable manner is to create your own facebook "app" and replace Dejan's keys for your own. I have been running his solution for months in a production environment without a single problem. You can see it here:

http://jamiescakedecorating.com.au/kids-cakes/

I'm sure the only reason Dejan left his keys in the source code was to allow for a quick and easy test to see if the album performs as per your own requirements and if you would like to invest the time to implement it into your setup. If you like the way the example works, it would take a whole 5 minutes to create a facebook app and get your own keys to make the API calls against, only then should you be attempting to pull your client's albums to get it to work.

**Comment by kawstuv** [comment]
I have generated my own access token and the way I have used it is
something like this:

$(document).ready(function () {
$(".fb-album-container").FacebookAlbumBrowser({
account: "DENTALSTUDIOKOLKATA",
accessToken: "775908159169504|cYEIsh0rs25OQQC8Ex2hXyCOut4",
skipAlbums: ["Profile Pictures", "Timeline Photos", "Photos", "Cover Photos",
"Mobile Uploads"],
thumbnailSize: 320,
showComments: false,
commentsLimit: 3,
showAccountInfo: false,
showImageCount: true,
showImageText: true,
shareButton: false,
albumsPageSize: 12,
photosPageSize: 12,
lightbox: true,
photosCheckbox: false,
pluginImagesPath: "src/",
likeButton: false,
shareButton: false,
addThis: "ra-52638e915dd79612",
photoChecked: function (photo) {
console.log("PHOTO CHECKED: " + photo.id + " - " + photo.url + " - " + photo
.thumb);
console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
},
photoUnchecked: function (photo) {
console.log("PHOTO UNCHECKED: " + photo.id + " - " + photo.url + " - " +
photo.thumb);
console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
},
albumSelected: function (photo) {
console.log("ALBUM CLICK: " + photo.id + " - " + photo.url + " - " + photo.
thumb);
},
photoSelected: function (photo) {
console.log("PHOTO CLICK: " + photo.id + " - " + photo.url + " - " + photo.
thumb);
}
});

});
}

Can you tell me where I am going wrong since it was functioning all okay
few days back

**Comment by zsavicreative** [comment]
so just for clarity, I'm putting your code in code tags for easier reading.

```
$(document).ready(function () {
  $(".fb-album-container").FacebookAlbumBrowser({
    account: "DENTALSTUDIOKOLKATA",
    accessToken: "775908159169504|cYEIsh0rs25OQQC8Ex2hXyCOut4",
    skipAlbums: ["Profile Pictures", "Timeline Photos", "Photos", "Cover Photos",
      "Mobile Uploads"
    ],
    thumbnailSize: 320,
    showComments: false,
    commentsLimit: 3,
    showAccountInfo: false,
    showImageCount: true,
    showImageText: true,
    shareButton: false,
    albumsPageSize: 12,
    photosPageSize: 12,
    lightbox: true,
    photosCheckbox: false,
    pluginImagesPath: "src/",
    likeButton: false,
    shareButton: false,
    addThis: "ra-52638e915dd79612",
    photoChecked: function (photo) {
      console.log("PHOTO CHECKED: " + photo.id + " - " + photo.url + " - " + photo
        .thumb);
      console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
    },
    photoUnchecked: function (photo) {
      console.log("PHOTO UNCHECKED: " + photo.id + " - " + photo.url + " - " +
        photo.thumb);
      console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
    },
    albumSelected: function (photo) {
      console.log("ALBUM CLICK: " + photo.id + " - " + photo.url + " - " + photo.thumb);
    },
    photoSelected: function (photo) {
      console.log("PHOTO CLICK: " + photo.id + " - " + photo.url + " - " + photo.thumb);
    }
  });

});
}
```

So first of all, your brackets are off, you've got an extra bracket at the bottom that is unnecessary.

The section that holds the options for the plugin should be as indicated below:

```
$(document).ready(function () {
  $(".fb-album-container").each(function () {
      $(this).FacebookAlbumBrowser({
          // all options in here.
      });
  });
});
```
Not sure how you had it working before, or if the code you've pasted here is exactly what you had before. But from a quick scan these two factors could be contributing to it not functioning as intended.

**Comment by kawstuv** [comment]
Sorry, I should have put the entire snippet. This is how I am using it.
<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
  <title>Untitled Document</title>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
  <script src="js/fbgallery.js"></script>
</head>

<body>
  <script>
    var appId = '193673707489176';
    var pageId = "428802613841578";
    var accessToken = '193673707489176|55a9bc60f1b35074263ea95e45218fc3';

    window.fbAsyncInit = function () {
      FB.init({
        appId: appId,
        xfbml: true,
        version: 'v2.8'
      });
      FB.AppEvents.logPageView();
      $("#mainContainer").fbGallery({
        accessToken: accessToken,
        pageId: pageId
      });
    };
    (function (d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) { return; }
      js = d.createElement(s); js.id = id;
      js.src = "https://connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  <style>
    body,
    html,
    #mainContainer {
      margin: 0;
      padding: 0;
    }
  </style>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36251023-1']);
    _gaq.push(['_setDomainName', 'jqueryscript.net']);
    _gaq.push(['_trackPageview']);

    (function () {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <script>
    if ($(window).width() > 739) {
      $(document).ready(function () {
        $(".fb-album-container").FacebookAlbumBrowser({
          account: "DENTALSTUDIOKOLKATA",
          accessToken: "775908159169504|cYEIsh0rs25OQQC8Ex2hXyCOut4",
          skipAlbums: ["Profile Pictures", "Timeline Photos", "Photos", "Cover Photos", "Mobile Uploads"],
          thumbnailSize: 320,
          showComments: false,
          commentsLimit: 3,
          showAccountInfo: false,
          showImageCount: true,
          showImageText: true,
          shareButton: false,
          albumsPageSize: 12,
          photosPageSize: 12,
          lightbox: true,
          photosCheckbox: false,
          pluginImagesPath: "src/",
          likeButton: false,
          shareButton: false,
          addThis: "ra-52638e915dd79612",
          photoChecked: function (photo) {
            console.log("PHOTO CHECKED: " + photo.id + " - " + photo.url + " - " + photo.thumb);
            console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
          },
          photoUnchecked: function (photo) {
            console.log("PHOTO UNCHECKED: " + photo.id + " - " + photo.url + " - " + photo.thumb);
            console.log("CHECKED PHOTOS COUNT: " + this.checkedPhotos.length);
          },
          albumSelected: function (photo) {
            console.log("ALBUM CLICK: " + photo.id + " - " + photo.url + " - " + photo.thumb);
          },
          photoSelected: function (photo) {
            console.log("PHOTO CLICK: " + photo.id + " - " + photo.url + " - " + photo.thumb);
          }
        });

      });
    }

  </script>
</body>

</html>

**Comment by zsavicreative** [comment]
I suggest you go back to the example provided in the source code and look at where you're going wrong. 

Also a piece of advice when creating posts on github projects, these are reserved for people who detect bugs and other underlining issues that the developer might not have come across in their development environment. If you require help in understanding how something works, then try creating a post on [https://stackoverflow.com/](url)

**Comment by kawstuv** [comment]
I will do that in future.

**Comment by Kurve** [comment]
Hi, we had this working on a couple of our websites until recently using our own Facebook Application and have found that we can only get the gallery working if we specify the 'onlyAlbum' attribute with a specified Facebook folder ID. When we try and use either the 'includeAlbums' or 'skipAlbums' we get nothing but the animated GIF.

The whole point of having this on our sites is so our Social Media Marketing Editor can upload images to Facebook in relevent folders so we don't have to replicate the process to get the images on our website(s). Having us add a folder each time we need to is just an extra process we can do without.

Any clues as to why these attributes have stopped working?

**Comment by ateufel** [comment]
guys...those are access tokens. NEVER hardcode any access token, and NEVER make any access token public...it should not even be in the demo. if you need to hardcode a token, do that server side only.
