### ISSUE TITLE
Linked facebook albums are not loading

### ISSUE THREAD

**Issue by kawstuv** [dejanstojanovic/Facebook-Album-Browser#71]
Thanks for the code it has been a great help, however, currently the facebook albums are not loading only the thumbnail appears. This is not only for me but everywhere it is happening wherever demo is given. Check this link:
http://demo.technoworkshop.in/facebook-album-browser/
https://www.jqueryscript.net/gallery/jQuery-Plugin-To-Display-Facebook-Albums-Photos-On-Your-Website.html
https://codepen.io/dejanstojanovic/full/qOERNz
http://www.webdesignfuel.com/demo/?t=facebook-photo-album-browser-reponsive-jquery-plugin&d=51

**Comment by ateufel** [comment]
if you try the base api call with an app access token, you will get the following error:

```
{
  "error": {
    "message": "(#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.",
    "type": "OAuthException",
    "code": 10,
    "fbtrace_id": "A2ElZv76sN4"
  }
}
```

you either need to review your app for that, or you can try with a page token. i would suggest programming that server side though, as i have pointed out elsewhere already, all tokens are meant to be kept secret.
