### ISSUE TITLE
Rate Limit Reached

### ISSUE THREAD

**Issue by khatau** [dejanstojanovic/Facebook-Album-Browser#73]
<img width="983" alt="screen shot 2018-08-26 at 16 37 48" src="https://user-images.githubusercontent.com/39865883/44628748-e2a7ef80-a94e-11e8-8a19-8f45fbee9b22.png">

**Comment by dejanstojanovic** [comment]
Think about building and intermediate proxy so you can cache your calls and avoid reaching the limit on the Facebook API
