### ISSUE TITLE
Position of the arrow left right of lightbox

### ISSUE THREAD

**Issue by lanner** [dejanstojanovic/Facebook-Album-Browser#8]
Hello :)
i have seen you have update the position of the arrows left and right, i think (it's my opinion) to have the arrows on the left/right  position:0 it's not really easy to use, maybe with a little screen but not on 1920 with full screen of chrome, and you can't change image if you click on the image (working with old release)

**Comment by lanner** [comment]
Solution to add and usefull : use the keyboard Arrow to change the images on lightbox :)

**Comment by dejanstojanovic** [comment]
I tried to avoid involving other plugins in the solution to keep it more clean, but it turns out I would have to re-write whole lightbox functionality :)

I'll add key handlers :+1:

**Comment by lanner** [comment]
hello
do you have update the key handlers in the latest update ?

**Comment by dejanstojanovic** [comment]
Sorry, no. Will do as soon as I get sime free time

**Comment by dejanstojanovic** [comment]
Left, right and escape key handlers are addes for lightbox preview
