### ISSUE TITLE
Lot of albums - pagination

### ISSUE THREAD

**Issue by lanner** [dejanstojanovic/Facebook-Album-Browser#9]
Hello :)
i don't have test but if you have lot of albums is it possible to add a pagination (or something similare) to only show a number of albums each time (with a parameter)

**Comment by lanner** [comment]
i have seen your upate for :
albumsPageSize: 0,  
photosPageSize: 0,  
But what with can do, cause i don't see nothing change :)

**Comment by dejanstojanovic** [comment]
Did no finish that functionality, just started coding.  I'll close thisbissue once it is done

**Comment by dejanstojanovic** [comment]
Dude, can you give me the account short name with large number of albums so I can test paging? The natgeo one has small number of albums so I cannot properly test

**Comment by dejanstojanovic** [comment]
I did an update. It is still not perfect as there are some small fine tuning to be done but basically it works for albums only for now

**Comment by dejanstojanovic** [comment]
Added paging for album and photo listing. Properties are listed and described in readme.md
